import type { Concept } from "./types";

export const concepts: Concept[] = [
  {
    slug: "dns",
    name: "DNS",
    category: "network",
    plain: "The internet's address book: it turns a name such as example.com into a server address.",
    engineering: "Resolvers follow cached and authoritative records to return IP addresses and related routing data.",
    production: "TTL choices balance quick failover against resolver load. Monitor resolution failures and protect registrar access.",
  },
  {
    slug: "cdn",
    name: "CDN",
    category: "network",
    plain: "A nearby delivery point that serves content without every visitor reaching the origin server.",
    engineering: "Edge locations cache responses by URL and cache policy, and may terminate TLS or run edge logic.",
    production: "Plan invalidation, cache keys, origin shielding, and safe fallbacks for stale content.",
  },
  {
    slug: "browser",
    name: "Browser",
    category: "client",
    plain: "The app on a person's device that requests, assembles, and displays a website.",
    engineering: "It parses HTML and CSS, executes JavaScript, builds render trees, and enforces web security boundaries.",
    production: "Test multiple engines, control bundle size, and observe real-user performance and client errors.",
  },
  {
    slug: "api",
    name: "API",
    category: "service",
    plain: "A documented doorway through which software asks other software to do something.",
    engineering: "An API defines operations, inputs, outputs, errors, authentication, and compatibility expectations.",
    production: "Version carefully, validate inputs, rate-limit abuse, trace calls, and publish an error contract.",
  },
  {
    slug: "authentication",
    name: "Authentication",
    category: "service",
    plain: "The process of proving who a person or system is.",
    engineering: "Authentication verifies credentials or delegated identity before issuing a session or token.",
    production: "Use hardened providers, MFA, throttling, audit trails, secure recovery, and short-lived credentials.",
  },
  {
    slug: "session",
    name: "Session",
    category: "service",
    plain: "A temporary record that lets a site remember that a user has already signed in.",
    engineering: "A browser usually holds an opaque cookie while the server stores or validates the session state.",
    production: "Rotate identifiers, use Secure/HttpOnly/SameSite cookies, expire sessions, and support revocation.",
  },
  {
    slug: "database",
    name: "Database",
    category: "database",
    plain: "A system designed to store information and retrieve it reliably.",
    engineering: "Databases provide data models, queries, indexes, concurrency rules, and durability guarantees.",
    production: "Back up and restore-test data, monitor slow queries, constrain access, and plan capacity and failover.",
  },
  {
    slug: "cache",
    name: "Cache",
    category: "cache",
    plain: "A fast temporary copy that avoids repeating slower work.",
    engineering: "Caches trade freshness and consistency for latency and reduced load using keys and expiry policies.",
    production: "Design for misses, stampedes, invalidation, eviction, and cache failure without losing source data.",
  },
  {
    slug: "queue",
    name: "Message queue",
    category: "queue",
    plain: "A waiting line that lets one part of a system hand work to another part for later processing.",
    engineering: "Producers publish messages; consumers acknowledge them after work, enabling buffering and retries.",
    production: "Handle duplicates, poison messages, back-pressure, ordering limits, retention, and dead-letter queues.",
  },
  {
    slug: "object-storage",
    name: "Object storage",
    category: "infrastructure",
    plain: "A durable home for files such as images, videos, and backups.",
    engineering: "Objects are addressed by keys and metadata through an HTTP API rather than a mounted filesystem.",
    production: "Use scoped signed access, lifecycle rules, encryption, replication, and deletion controls.",
  },
  {
    slug: "worker",
    name: "Background worker",
    category: "service",
    plain: "A program that handles tasks away from the user-facing request.",
    engineering: "Workers consume queued jobs, apply idempotent processing, and acknowledge success or retry failure.",
    production: "Autoscale on queue depth, cap retries, expose job latency, and isolate expensive or unsafe work.",
  },
  {
    slug: "load-balancer",
    name: "Load balancer",
    category: "network",
    plain: "A traffic director that spreads incoming requests across healthy servers.",
    engineering: "It chooses a backend using health, routing rules, and an algorithm such as round-robin or least connections.",
    production: "Test health checks, connection draining, zone failure, TLS policy, and overload behavior.",
  },
  {
    slug: "replica",
    name: "Service replica",
    category: "infrastructure",
    plain: "Another running copy of a service that can share work or take over when one copy fails.",
    engineering: "Stateless replicas can receive any request when shared state lives in external systems.",
    production: "Use readiness checks, disruption budgets, balanced placement, and capacity headroom.",
  },
  {
    slug: "read-replica",
    name: "Database read replica",
    category: "database",
    plain: "A copy of a database used mainly to answer reads and reduce pressure on the primary.",
    engineering: "Changes stream from the primary, usually with some replication delay, so reads may be stale.",
    production: "Measure lag, route consistency-sensitive reads to primary, and rehearse promotion/failover.",
  },
  {
    slug: "container",
    name: "Container",
    category: "infrastructure",
    plain: "A portable package containing an application and the files it needs to run.",
    engineering: "Container images provide repeatable user-space dependencies while sharing the host kernel.",
    production: "Pin and scan images, run without root, set resource limits, and keep runtime state external.",
  },
  {
    slug: "ci",
    name: "Continuous integration",
    category: "infrastructure",
    plain: "An automated checkpoint that builds and tests every proposed code change.",
    engineering: "CI creates repeatable pipelines for validation, artifacts, and policy enforcement.",
    production: "Use isolated runners, protected secrets, pinned actions, provenance, and fast deterministic checks.",
  },
  {
    slug: "deployment",
    name: "Deployment",
    category: "infrastructure",
    plain: "The controlled process of putting a tested application version into an environment.",
    engineering: "A deployment promotes an immutable artifact through configuration and rollout steps.",
    production: "Prefer gradual rollout, health gates, observability, backward compatibility, and fast rollback.",
  },
  {
    slug: "observability",
    name: "Observability",
    category: "observability",
    plain: "The signals that help a team understand what a running system is doing.",
    engineering: "Logs, metrics, and traces connect events, trends, and request paths to system behavior.",
    production: "Instrument user outcomes, define service objectives, control cardinality, and make alerts actionable.",
  },
  {
    slug: "http",
    name: "HTTP request",
    category: "foundation",
    plain: "A structured message a client sends to ask a server for a resource or action.",
    engineering: "HTTP combines a method, URL, headers, and optional body with a status, headers, and response body.",
    production: "Set timeouts, retries only when safe, size limits, TLS, caching rules, and correlation identifiers.",
  },
  {
    slug: "telemetry",
    name: "Telemetry",
    category: "observability",
    plain: "Measurements a system emits about its work and health.",
    engineering: "Applications emit structured logs, counters, histograms, events, and trace spans.",
    production: "Avoid secrets and personal data, sample intentionally, standardize fields, and budget ingestion cost.",
  },
];
