import type { Lesson, LessonSummary, NodeKind, SystemNode } from "./types";

const node = (
  id: string,
  label: string,
  kind: NodeKind,
  x: number,
  y: number,
  summary: string,
  engineering: string,
  production: string,
  concept?: string,
  alternatives?: string[],
): SystemNode => ({
  id,
  label,
  kind,
  position: { x, y },
  summary,
  engineering,
  production,
  concept,
  alternatives,
});

export const lessons: Lesson[] = [
  {
    schemaVersion: 1,
    slug: "loading-a-web-page",
    title: "What happens when a page loads?",
    eyebrow: "Web foundations",
    summary: "Follow a URL from a browser through DNS and a CDN to the origin—and back as a rendered page.",
    audience: ["beginner", "developer"],
    duration: 7,
    difficulty: 1,
    topics: ["Frontend", "Networking", "Web"],
    prerequisites: [],
    learningObjectives: ["Order the major page-load stages", "Explain why DNS and a CDN exist", "Distinguish a request from a response"],
    nodes: [
      node("browser", "Browser", "client", 0, 130, "Turns a URL into a visible, interactive page.", "Parses HTML/CSS, executes JavaScript, and schedules network and rendering work.", "Measure real-user loading, keep bundles small, and support multiple engines.", "browser", ["Native app", "Command-line client"]),
      node("dns", "DNS resolver", "network", 240, 0, "Finds the network address behind a domain name.", "Uses cached recursive lookups and authoritative records.", "Protect registrar access and choose TTLs that support recovery.", "dns"),
      node("cdn", "CDN edge", "network", 480, 130, "Serves a nearby cached response when possible.", "Terminates TLS and applies cache rules before contacting the origin.", "Design cache keys, invalidation, shielding, and stale fallbacks.", "cdn", ["Direct origin", "Reverse proxy"]),
      node("origin", "Web origin", "service", 720, 130, "Produces the page when the edge has no usable copy.", "Routes the request and returns static or rendered HTML and assets.", "Use timeouts, autoscaling, health checks, and safe cache headers.", "api"),
      node("telemetry", "Web telemetry", "observability", 720, 320, "Records whether the experience worked for real users.", "Collects performance entries, errors, logs, and traces.", "Avoid personal data and alert on user outcomes rather than noise.", "telemetry"),
    ],
    edges: [
      { id: "browser-dns", source: "browser", target: "dns", label: "resolve domain", kind: "request" },
      { id: "browser-cdn", source: "browser", target: "cdn", label: "HTTPS request", kind: "request" },
      { id: "cdn-origin", source: "cdn", target: "origin", label: "cache miss", kind: "request" },
      { id: "origin-cdn", source: "origin", target: "cdn", label: "HTML + assets", kind: "response" },
      { id: "cdn-browser", source: "cdn", target: "browser", label: "response", kind: "response" },
      { id: "browser-telemetry", source: "browser", target: "telemetry", label: "web vitals", kind: "telemetry" },
    ],
    steps: [
      { id: "resolve", title: "Find the address", narration: "The browser asks DNS which network address serves the domain.", activeNodeIds: ["browser", "dns"], activeEdgeIds: ["browser-dns"], payload: { label: "Domain: stackscope.dev" }, failure: "A bad or unavailable DNS record means the journey cannot start.", observation: "DNS lookup duration and failure rate." },
      { id: "request", title: "Request the page", narration: "The browser opens a secure connection and sends an HTTP request to a nearby CDN edge.", activeNodeIds: ["browser", "cdn"], activeEdgeIds: ["browser-cdn"], payload: { label: "GET /learn · Accept: text/html" }, failure: "TLS, connectivity, or routing can fail before application code runs.", observation: "Connection and time-to-first-byte timing." },
      { id: "miss", title: "Reach the origin", narration: "On a cache miss, the CDN forwards the request to the web origin.", activeNodeIds: ["cdn", "origin"], activeEdgeIds: ["cdn-origin"], payload: { label: "Forwarded request + cache context" }, failure: "An overloaded origin makes uncached traffic slow or unavailable.", observation: "Cache hit ratio and origin latency." },
      { id: "return", title: "Return and cache", narration: "The origin responds; the CDN may store a reusable copy and forwards it to the browser.", activeNodeIds: ["origin", "cdn", "browser"], activeEdgeIds: ["origin-cdn", "cdn-browser"], payload: { label: "200 OK · HTML, CSS and JavaScript" }, failure: "Incorrect cache policy can serve stale or private content.", observation: "Status code, response size, and cache status." },
      { id: "render", title: "Render and measure", narration: "The browser builds the page, runs its code, and reports experience signals.", activeNodeIds: ["browser", "telemetry"], activeEdgeIds: ["browser-telemetry"], payload: { label: "LCP, INP, CLS and client errors" }, failure: "A successful HTTP response can still produce a slow or broken experience.", observation: "Real-user web vitals and JavaScript errors." },
    ],
    glossaryRefs: ["browser", "dns", "cdn", "http", "telemetry"],
    checks: [
      { objectiveIndex: 0, question: "Which stage happens before the browser can contact the site?", options: ["JavaScript execution", "DNS resolution", "Database indexing", "Image processing"], answer: 1, explanation: "DNS resolves the domain to a network address before the HTTP connection starts." },
      { objectiveIndex: 1, question: "Why can a CDN answer without contacting the origin?", options: ["It owns DNS", "It has a valid cached response", "It runs the browser", "It stores user passwords"], answer: 1, explanation: "A CDN can reuse a response while its cache policy says the response is still valid." },
      { objectiveIndex: 2, question: "Which message travels back toward the browser?", options: ["An HTTP response", "A DNS registration", "A database transaction", "A CI artifact"], answer: 0, explanation: "The request travels toward the server; the HTTP response carries status, headers, and content back." },
    ],
    simplification: "Browsers usually request many assets in parallel and may use service workers, multiple caches, redirects, and modern connection protocols.",
    owner: "StackScope editorial",
    sources: [
      { label: "MDN: How browsers work", url: "https://developer.mozilla.org/en-US/docs/Web/Performance/Guides/How_browsers_work" },
      { label: "MDN: HTTP caching", url: "https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Caching" },
    ],
    reviewedAt: "2026-07-10",
  },
  {
    schemaVersion: 1,
    slug: "signing-in",
    title: "What happens when you sign in?",
    eyebrow: "Identity & security",
    summary: "Trace credentials through a frontend and API to identity verification and a secure session.",
    audience: ["beginner", "developer"],
    duration: 8,
    difficulty: 1,
    topics: ["Frontend", "Backend", "Security"],
    prerequisites: ["loading-a-web-page"],
    learningObjectives: ["Separate authentication from session use", "Locate trust boundaries", "Explain why passwords are never returned"],
    nodes: [
      node("browser", "Browser", "client", 0, 130, "Collects credentials and later stores a protected session cookie.", "Submits over HTTPS and follows cookie security rules.", "Prevent injection, avoid logging secrets, and support secure recovery.", "browser"),
      node("frontend", "Frontend", "service", 230, 130, "Presents the form and sends the sign-in request.", "Performs usability validation but never replaces server validation.", "Deploy CSP, CSRF defenses, dependency controls, and client monitoring.", "http"),
      node("api", "Auth API", "service", 470, 130, "Validates the request and coordinates identity verification.", "Applies rate limits, schema checks, and a stable error contract.", "Keep responses non-enumerating and audit security events.", "api"),
      node("identity", "Identity service", "service", 710, 0, "Checks the submitted proof of identity.", "Compares a password hash or verifies an external identity assertion.", "Prefer hardened providers, MFA, breach controls, and secure recovery.", "authentication"),
      node("users", "User database", "database", 710, 250, "Stores identity records and password verifiers—not plain passwords.", "Uses salted password hashes and constrained queries.", "Encrypt backups, restrict access, audit reads, and restore-test.", "database"),
      node("sessions", "Session store", "cache", 950, 130, "Stores short-lived sign-in state behind an opaque identifier.", "Maps a random cookie value to server-side identity and expiry.", "Rotate, expire, revoke, replicate, and monitor session creation.", "session", ["Signed stateless token"]),
    ],
    edges: [
      { id: "browser-frontend", source: "browser", target: "frontend", label: "credentials", kind: "request" },
      { id: "frontend-api", source: "frontend", target: "api", label: "POST /session", kind: "request" },
      { id: "api-identity", source: "api", target: "identity", label: "verify", kind: "request" },
      { id: "identity-users", source: "identity", target: "users", label: "lookup verifier", kind: "query" },
      { id: "api-sessions", source: "api", target: "sessions", label: "create session", kind: "query" },
      { id: "sessions-browser", source: "sessions", target: "browser", label: "secure cookie", kind: "response" },
    ],
    steps: [
      { id: "collect", title: "Collect securely", narration: "The browser collects the sign-in proof and submits it over HTTPS.", activeNodeIds: ["browser", "frontend"], activeEdgeIds: ["browser-frontend"], payload: { label: "Email + password over an encrypted connection" }, failure: "Injected scripts or fake pages can steal credentials before submission.", observation: "Client error and form completion rate—never password contents." },
      { id: "validate", title: "Validate and limit", narration: "The API validates the shape and applies abuse controls before expensive verification.", activeNodeIds: ["frontend", "api"], activeEdgeIds: ["frontend-api"], payload: { label: "POST /session · request ID" }, failure: "Missing throttling enables credential stuffing and denial of service.", observation: "Attempt rate, throttle decisions, and generic failure count." },
      { id: "verify", title: "Verify identity", narration: "The identity service loads the stored verifier and performs a constant-behavior check.", activeNodeIds: ["api", "identity", "users"], activeEdgeIds: ["api-identity", "identity-users"], payload: { label: "User lookup + password hash verification" }, failure: "Weak hashing or account-specific errors expose users and passwords.", observation: "Verification latency and security audit event." },
      { id: "session", title: "Create a session", narration: "After success, the API creates a short-lived session represented by a random identifier.", activeNodeIds: ["api", "sessions"], activeEdgeIds: ["api-sessions"], payload: { label: "Session ID, user ID, expiry" }, failure: "Predictable or long-lived sessions enable hijacking.", observation: "Session creation, expiry, and revocation events." },
      { id: "cookie", title: "Return the cookie", narration: "The browser receives an opaque Secure, HttpOnly session cookie; it never receives the password back.", activeNodeIds: ["sessions", "browser"], activeEdgeIds: ["sessions-browser"], payload: { label: "Set-Cookie: session=opaque; Secure; HttpOnly" }, failure: "Weak cookie settings expose the session to scripts or insecure transport.", observation: "Successful sign-in and subsequent authorized request." },
    ],
    glossaryRefs: ["authentication", "session", "api", "database", "browser"],
    checks: [
      { objectiveIndex: 0, question: "What is authentication doing during sign-in?", options: ["Compressing the page", "Proving an identity", "Scaling the database", "Caching an image"], answer: 1, explanation: "Authentication verifies a person's or system's claimed identity." },
      { objectiveIndex: 1, question: "What should the browser keep after a successful server-side session login?", options: ["The password hash", "A database connection", "An opaque secure session cookie", "The identity database"], answer: 2, explanation: "The browser keeps an opaque identifier; sensitive identity state remains server-side." },
      { objectiveIndex: 2, question: "Why is the password never returned to the browser?", options: ["The server only needs a proof and session result", "DNS removes it", "The CDN encrypts it forever", "The database cannot read text"], answer: 0, explanation: "Credentials are verified once; subsequent requests use the protected session rather than returning or resending the password." },
    ],
    simplification: "Real systems may redirect to an external identity provider, use passkeys or MFA, manage CSRF tokens, and separate identity from session services.",
    owner: "StackScope editorial",
    sources: [
      { label: "OWASP Authentication Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html" },
      { label: "OWASP Session Management Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Session_Management_Cheat_Sheet.html" },
    ],
    reviewedAt: "2026-07-10",
  },
  {
    schemaVersion: 1,
    slug: "reading-a-dashboard",
    title: "How does a dashboard get its data?",
    eyebrow: "Backend request path",
    summary: "See an API gateway, service, cache, and database cooperate to return useful data quickly.",
    audience: ["beginner", "developer"],
    duration: 7,
    difficulty: 2,
    topics: ["Backend", "Caching", "Data"],
    prerequisites: ["loading-a-web-page"],
    learningObjectives: ["Explain a cache hit and miss", "Identify the source of truth", "Place latency observations"],
    nodes: [
      node("browser", "Dashboard", "client", 0, 120, "Requests the data needed for the current view.", "Sends an authorized API request and renders partial states.", "Handle slow, empty, stale, and failed responses explicitly.", "browser"),
      node("gateway", "API gateway", "network", 230, 120, "Routes and protects the request.", "Terminates TLS, verifies policy, and forwards context.", "Use bounded timeouts, rate limits, and trace propagation.", "api"),
      node("service", "Dashboard service", "service", 470, 120, "Coordinates the business query.", "Builds a cache key, applies authorization, and shapes output.", "Keep instances stateless and cap downstream work.", "api"),
      node("cache", "Response cache", "cache", 710, 0, "Returns a recent answer quickly when available.", "Stores serialized results under a key with an expiry.", "Design misses, invalidation, and stampede protection.", "cache"),
      node("db", "Primary database", "database", 710, 250, "Holds the authoritative dashboard records.", "Uses indexes and transactions to answer the query.", "Monitor query plans, pool limits, backups, and locks.", "database"),
      node("metrics", "Request telemetry", "observability", 950, 120, "Shows where time and failures occur.", "Correlates gateway, service, cache, and database spans.", "Alert on user-facing latency and errors by operation.", "observability"),
    ],
    edges: [
      { id: "browser-gateway", source: "browser", target: "gateway", label: "GET /dashboard", kind: "request" },
      { id: "gateway-service", source: "gateway", target: "service", label: "authorized request", kind: "request" },
      { id: "service-cache", source: "service", target: "cache", label: "lookup", kind: "query" },
      { id: "service-db", source: "service", target: "db", label: "cache miss query", kind: "query" },
      { id: "db-cache", source: "db", target: "cache", label: "fresh result", kind: "response" },
      { id: "service-metrics", source: "service", target: "metrics", label: "trace + metrics", kind: "telemetry" },
      { id: "service-browser", source: "service", target: "browser", label: "dashboard JSON", kind: "response" },
    ],
    steps: [
      { id: "enter", title: "Enter through the gateway", narration: "The dashboard sends an authorized request through the system's controlled entry point.", activeNodeIds: ["browser", "gateway", "service"], activeEdgeIds: ["browser-gateway", "gateway-service"], payload: { label: "GET /dashboard?range=7d" }, failure: "Invalid identity, throttling, or routing can reject the call early.", observation: "Gateway status, route, and total latency." },
      { id: "cache", title: "Try the fast path", narration: "The service asks the cache whether this user and date range already have a recent result.", activeNodeIds: ["service", "cache"], activeEdgeIds: ["service-cache"], payload: { label: "Key: dashboard:user-42:7d" }, failure: "A cache outage must degrade to a safe miss rather than lose data.", observation: "Hit ratio and cache operation latency." },
      { id: "query", title: "Use the source of truth", narration: "On a miss, the service runs a bounded, indexed database query.", activeNodeIds: ["service", "db"], activeEdgeIds: ["service-db"], payload: { label: "Parameterized aggregate query" }, failure: "Missing indexes or pool exhaustion can make every request slow.", observation: "Query duration, rows examined, and connection wait." },
      { id: "fill", title: "Fill the cache", narration: "The fresh database result is stored briefly so nearby requests can reuse it.", activeNodeIds: ["db", "cache"], activeEdgeIds: ["db-cache"], payload: { label: "Dashboard result · TTL 60 seconds" }, failure: "A poor key can leak or mix tenant data; a long TTL can serve stale results.", observation: "Fill rate, evictions, and freshness age." },
      { id: "respond", title: "Respond and trace", narration: "The service returns shaped JSON while emitting a trace across every dependency.", activeNodeIds: ["service", "browser", "metrics"], activeEdgeIds: ["service-browser", "service-metrics"], payload: { label: "200 OK · dashboard cards" }, failure: "A technically successful response may still be incomplete or too slow.", observation: "End-to-end latency, error rate, and result cardinality." },
    ],
    glossaryRefs: ["api", "cache", "database", "observability", "http"],
    checks: [
      { objectiveIndex: 0, question: "What does a cache hit avoid?", options: ["A browser render", "A repeated database query", "A DNS record", "A deployment"], answer: 1, explanation: "A hit reuses the recent cached result instead of repeating the slower source query." },
      { objectiveIndex: 1, question: "Which component remains the source of truth when the response cache is empty?", options: ["The browser", "The gateway", "The primary database", "The metrics store"], answer: 2, explanation: "The cache is disposable; the database holds the authoritative records." },
      { objectiveIndex: 2, question: "Which signal best exposes a slow database dependency?", options: ["The logo color", "A traced query duration", "The browser width", "The cache key name"], answer: 1, explanation: "A trace connects overall request latency to the database span that consumed the time." },
    ],
    simplification: "A real dashboard may call several services, stream partial data, precompute aggregates, and apply row-level authorization at multiple layers.",
    owner: "StackScope editorial",
    sources: [
      { label: "AWS: Caching best practices", url: "https://docs.aws.amazon.com/whitepapers/latest/database-caching-strategies-using-redis/caching-best-practices.html" },
      { label: "PostgreSQL: Indexes", url: "https://www.postgresql.org/docs/current/indexes.html" },
    ],
    reviewedAt: "2026-07-10",
  },
  {
    schemaVersion: 1,
    slug: "processing-an-image",
    title: "How is an uploaded image processed?",
    eyebrow: "Asynchronous systems",
    summary: "Follow a direct upload into object storage, through a queue and worker, then out through a CDN.",
    audience: ["beginner", "developer"],
    duration: 8,
    difficulty: 2,
    topics: ["Backend", "Queues", "Storage"],
    prerequisites: ["reading-a-dashboard"],
    learningObjectives: ["Explain direct upload", "Describe producer/consumer separation", "Recognize retry and duplicate risks"],
    nodes: [
      node("browser", "Uploader", "client", 0, 150, "Lets the user choose and upload an image.", "Requests scoped upload permission and transfers bytes directly.", "Validate size/type, show progress, and recover interrupted uploads.", "browser"),
      node("api", "Media API", "service", 220, 0, "Authorizes the upload and creates its record.", "Issues a short-lived signed upload URL with constraints.", "Enforce ownership, quotas, and idempotent completion.", "api"),
      node("storage", "Object storage", "infrastructure", 460, 150, "Durably stores the original and processed files.", "Accepts signed HTTP uploads and emits object-created events.", "Use encryption, lifecycle rules, scoped access, and replication.", "object-storage"),
      node("queue", "Job queue", "queue", 700, 150, "Buffers processing work until a worker is ready.", "Delivers at least once and requires consumer acknowledgement.", "Track depth, age, retries, poison jobs, and dead letters.", "queue"),
      node("worker", "Image worker", "service", 940, 150, "Creates safe, optimized image variants.", "Downloads the original, validates it, transforms it, and writes outputs idempotently.", "Sandbox codecs, cap resources, autoscale, and tolerate duplicates.", "worker"),
      node("cdn", "Image CDN", "network", 1180, 150, "Delivers processed images close to viewers.", "Caches immutable variant URLs at edge locations.", "Use versioned keys and protect the storage origin.", "cdn"),
    ],
    edges: [
      { id: "browser-api", source: "browser", target: "api", label: "request upload", kind: "request" },
      { id: "browser-storage", source: "browser", target: "storage", label: "signed upload", kind: "artifact" },
      { id: "storage-queue", source: "storage", target: "queue", label: "object-created", kind: "event" },
      { id: "queue-worker", source: "queue", target: "worker", label: "process job", kind: "event" },
      { id: "worker-storage", source: "worker", target: "storage", label: "write variants", kind: "artifact" },
      { id: "storage-cdn", source: "storage", target: "cdn", label: "serve variant", kind: "response" },
      { id: "cdn-browser", source: "cdn", target: "browser", label: "optimized image", kind: "response" },
    ],
    steps: [
      { id: "authorize", title: "Authorize the upload", narration: "The app requests a short-lived, narrowly scoped upload URL.", activeNodeIds: ["browser", "api"], activeEdgeIds: ["browser-api"], payload: { label: "Filename, content type, size, checksum" }, failure: "Broad or long-lived permission lets an attacker overwrite or upload arbitrary objects.", observation: "Upload grants, rejections, and quota use." },
      { id: "upload", title: "Upload directly", narration: "The browser sends large bytes straight to object storage instead of through the API.", activeNodeIds: ["browser", "storage"], activeEdgeIds: ["browser-storage"], payload: { label: "Image bytes + signed constraints" }, failure: "Interrupted uploads need retry or multipart recovery.", observation: "Upload duration, bytes, and checksum result." },
      { id: "enqueue", title: "Queue the work", narration: "The new object emits an event that becomes a durable processing job.", activeNodeIds: ["storage", "queue"], activeEdgeIds: ["storage-queue"], payload: { label: "Object key, owner, job ID" }, failure: "Duplicate delivery is normal, so processing cannot assume exactly once.", observation: "Queue depth, oldest job age, and publish failures." },
      { id: "process", title: "Process safely", narration: "A worker validates the file and creates deterministic sizes and formats.", activeNodeIds: ["queue", "worker", "storage"], activeEdgeIds: ["queue-worker", "worker-storage"], payload: { label: "Original → thumbnail, web, retina" }, failure: "Malformed media can exhaust memory or exploit unsafe codecs.", observation: "Job latency, retry count, resource use, and output checksum." },
      { id: "deliver", title: "Deliver the result", narration: "Immutable variants are cached by the CDN and returned efficiently.", activeNodeIds: ["storage", "cdn", "browser"], activeEdgeIds: ["storage-cdn", "cdn-browser"], payload: { label: "GET /images/id/version.webp" }, failure: "Mutable URLs create stale-cache ambiguity after reprocessing.", observation: "Variant hit ratio, transfer size, and viewer latency." },
    ],
    glossaryRefs: ["object-storage", "queue", "worker", "cdn", "api"],
    checks: [
      { objectiveIndex: 0, question: "Why upload large image bytes directly to object storage?", options: ["To bypass authorization", "To avoid routing large transfers through the API", "To remove checksums", "To make files public"], answer: 1, explanation: "The API can authorize a narrow upload while storage handles the large byte transfer efficiently." },
      { objectiveIndex: 1, question: "What separates upload acceptance from image processing?", options: ["A message queue", "A CSS file", "DNS", "A browser cookie"], answer: 0, explanation: "The queue buffers a durable job until a worker has capacity." },
      { objectiveIndex: 2, question: "Why must the image worker tolerate the same job more than once?", options: ["Browsers duplicate every upload", "Queues may redeliver unacknowledged work", "CDNs require two files", "Databases cannot store images"], answer: 1, explanation: "Most durable queues prefer possible redelivery over silently losing work, so consumers should be idempotent." },
    ],
    simplification: "Virus scanning, moderation, metadata stripping, multipart uploads, job callbacks, and cleanup workflows are omitted.",
    owner: "StackScope editorial",
    sources: [
      { label: "AWS S3: Presigned URLs", url: "https://docs.aws.amazon.com/AmazonS3/latest/userguide/using-presigned-url.html" },
      { label: "AWS SQS: At-least-once delivery", url: "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/standard-queues-at-least-once-delivery.html" },
    ],
    reviewedAt: "2026-07-10",
  },
  {
    schemaVersion: 1,
    slug: "deploying-an-application",
    title: "How does code reach production?",
    eyebrow: "Delivery & operations",
    summary: "Move a commit through CI, an immutable artifact, a gradual rollout, and production observation.",
    audience: ["beginner", "developer"],
    duration: 9,
    difficulty: 2,
    topics: ["Deployment", "CI/CD", "Observability"],
    prerequisites: ["loading-a-web-page"],
    learningObjectives: ["Separate build from deploy", "Explain immutable artifacts", "Describe a safe rollout and rollback"],
    nodes: [
      node("git", "Source control", "infrastructure", 0, 140, "Records reviewed code and its history.", "A commit identifies the exact source used by the pipeline.", "Protect branches, require review, sign releases, and restrict automation tokens.", "ci"),
      node("ci", "CI pipeline", "infrastructure", 230, 140, "Checks the change and builds it once.", "Runs deterministic lint, tests, type checks, security checks, and packaging.", "Isolate runners, pin dependencies, and protect secrets and provenance.", "ci"),
      node("registry", "Artifact registry", "infrastructure", 470, 140, "Stores the exact deployable build.", "Publishes an immutable image or bundle keyed by digest.", "Scan, sign, retain, replicate, and control promotion permissions.", "container"),
      node("platform", "Deployment platform", "infrastructure", 710, 140, "Replaces old instances gradually with the new artifact.", "Applies configuration, starts replicas, and waits for readiness.", "Use staged rollout, disruption limits, compatibility checks, and rollback.", "deployment"),
      node("service", "Production service", "service", 950, 40, "Serves real traffic on the new version.", "Replicas receive traffic only after health and readiness gates.", "Maintain capacity headroom and backward-compatible data changes.", "replica"),
      node("observe", "Observability", "observability", 950, 260, "Shows whether the release improved or harmed user outcomes.", "Compares errors, latency, saturation, and business signals by version.", "Automate rollback on strong signals and keep human context available.", "observability"),
    ],
    edges: [
      { id: "git-ci", source: "git", target: "ci", label: "commit", kind: "artifact" },
      { id: "ci-registry", source: "ci", target: "registry", label: "signed artifact", kind: "artifact" },
      { id: "registry-platform", source: "registry", target: "platform", label: "deploy digest", kind: "artifact" },
      { id: "platform-service", source: "platform", target: "service", label: "gradual rollout", kind: "artifact" },
      { id: "service-observe", source: "service", target: "observe", label: "runtime signals", kind: "telemetry" },
      { id: "observe-platform", source: "observe", target: "platform", label: "continue / rollback", kind: "event" },
    ],
    steps: [
      { id: "commit", title: "Start from reviewed source", narration: "A protected branch records the exact approved commit.", activeNodeIds: ["git", "ci"], activeEdgeIds: ["git-ci"], payload: { label: "Commit SHA + review metadata" }, failure: "Unreviewed or mutable inputs make releases hard to trust or reproduce.", observation: "Pipeline trigger and source identity." },
      { id: "verify", title: "Verify and build once", narration: "CI runs required checks and creates one deployable artifact.", activeNodeIds: ["ci"], activeEdgeIds: [], payload: { label: "Lint + types + unit + integration + build" }, failure: "Flaky or environment-dependent checks weaken the gate.", observation: "Duration, failure class, flake rate, and coverage of critical paths." },
      { id: "publish", title: "Publish immutably", narration: "The artifact is signed and stored by digest; environments promote the same bytes.", activeNodeIds: ["ci", "registry"], activeEdgeIds: ["ci-registry"], payload: { label: "Image digest + SBOM + provenance" }, failure: "Rebuilding per environment can produce different, unaudited outputs.", observation: "Artifact digest, scan result, and signature verification." },
      { id: "rollout", title: "Roll out gradually", narration: "The platform starts a small number of new replicas and waits for readiness before adding traffic.", activeNodeIds: ["registry", "platform", "service"], activeEdgeIds: ["registry-platform", "platform-service"], payload: { label: "Version, config reference, rollout policy" }, failure: "Incompatible data or false health checks can turn a small change into an outage.", observation: "Ready replicas, rollout stage, and version traffic share." },
      { id: "decide", title: "Observe and decide", narration: "Version-aware signals decide whether to continue or roll back to the known-good digest.", activeNodeIds: ["service", "observe", "platform"], activeEdgeIds: ["service-observe", "observe-platform"], payload: { label: "Errors, latency, saturation, user success" }, failure: "Missing version tags hide whether the release caused the regression.", observation: "Service objectives and rollback action." },
    ],
    glossaryRefs: ["ci", "container", "deployment", "observability", "replica"],
    checks: [
      { objectiveIndex: 0, question: "Which stage creates the deployable artifact?", options: ["The production browser", "The CI build", "The load balancer", "The metrics store"], answer: 1, explanation: "CI verifies the source and creates the immutable artifact before deployment." },
      { objectiveIndex: 1, question: "Why promote the same immutable artifact between environments?", options: ["To avoid all configuration", "To ensure the tested bytes are the deployed bytes", "To remove source control", "To eliminate monitoring"], answer: 1, explanation: "One immutable digest reduces drift and connects verification evidence to the deployed software." },
      { objectiveIndex: 2, question: "What makes a gradual rollout safer?", options: ["It removes monitoring", "It exposes a small traffic share before full release", "It rebuilds on every server", "It deletes the previous version"], answer: 1, explanation: "A small initial traffic share limits impact and creates time to observe or roll back." },
    ],
    simplification: "Approval policies, infrastructure changes, feature flags, database migration sequencing, secrets, and multi-region delivery are omitted.",
    owner: "StackScope editorial",
    sources: [
      { label: "SLSA: Build provenance", url: "https://slsa.dev/spec/v1.2/provenance" },
      { label: "Kubernetes: Deployments", url: "https://kubernetes.io/docs/concepts/workloads/controllers/deployment/" },
    ],
    reviewedAt: "2026-07-10",
  },
  {
    schemaVersion: 1,
    slug: "scaling-a-service",
    title: "How does a service scale?",
    eyebrow: "Production architecture",
    summary: "Grow from one service to balanced replicas, cache, read capacity, and buffered background work.",
    audience: ["beginner", "developer"],
    duration: 10,
    difficulty: 3,
    topics: ["Architecture", "Scaling", "Reliability"],
    prerequisites: ["reading-a-dashboard", "processing-an-image"],
    learningObjectives: ["Explain horizontal scaling", "Separate synchronous and asynchronous work", "Recognize consistency trade-offs"],
    nodes: [
      node("client", "Clients", "client", 0, 150, "Generate requests with changing traffic patterns.", "Use bounded timeouts and safe retries.", "Protect users from overload with clear failure and recovery states.", "browser"),
      node("lb", "Load balancer", "network", 220, 150, "Routes each request to a healthy service copy.", "Uses health and routing rules without owning business state.", "Test zone failure, draining, overload, and TLS policy.", "load-balancer"),
      node("replicas", "Application service", "service", 460, 150, "Runs one or more stateless copies of the same code.", "Externalizes shared state so any healthy instance can serve a request.", "Scales on demand and saturation with headroom and disruption limits.", "replica"),
      node("cache", "Shared cache", "cache", 700, 0, "Absorbs repeated hot reads.", "Stores derived data with explicit freshness rules.", "Prevent stampedes and degrade safely on loss.", "cache"),
      node("primary", "Primary database", "database", 700, 220, "Accepts authoritative writes and consistent reads.", "Commits transactions and streams changes to replicas.", "Protect write capacity, backups, locks, and failover.", "database"),
      node("reader", "Read replica", "database", 930, 40, "Adds read capacity with some replication delay.", "Serves consistency-tolerant queries from an asynchronously updated copy.", "Measure lag and route read-after-write traffic carefully.", "read-replica"),
      node("queue", "Work queue", "queue", 930, 280, "Buffers slow work outside the request path.", "Decouples request acceptance from idempotent processing.", "Autoscale on age/depth and bound retries.", "queue"),
      node("observe", "Scaling signals", "observability", 1160, 150, "Shows which resource is actually saturated.", "Combines demand, latency, errors, utilization, queue age, and database pressure.", "Scale against service objectives, not one noisy metric.", "observability"),
    ],
    edges: [
      { id: "client-replicas", source: "client", target: "replicas", label: "direct request", kind: "request" },
      { id: "client-lb", source: "client", target: "lb", label: "requests", kind: "request" },
      { id: "lb-replicas", source: "lb", target: "replicas", label: "healthy route", kind: "request" },
      { id: "replicas-cache", source: "replicas", target: "cache", label: "hot reads", kind: "query" },
      { id: "replicas-primary", source: "replicas", target: "primary", label: "writes", kind: "query" },
      { id: "primary-reader", source: "primary", target: "reader", label: "replication", kind: "event" },
      { id: "replicas-reader", source: "replicas", target: "reader", label: "tolerant reads", kind: "query" },
      { id: "replicas-queue", source: "replicas", target: "queue", label: "slow work", kind: "event" },
      { id: "replicas-observe", source: "replicas", target: "observe", label: "service signals", kind: "telemetry" },
      { id: "queue-observe", source: "queue", target: "observe", label: "age + depth", kind: "telemetry" },
    ],
    steps: [
      { id: "balance", title: "Balance traffic", narration: "A load balancer spreads demand across healthy, interchangeable service replicas.", activeNodeIds: ["client", "lb", "replicas"], activeEdgeIds: ["client-lb", "lb-replicas"], payload: { label: "Request + routing context" }, failure: "State tied to one replica makes failover and balancing unreliable.", observation: "Request rate, healthy targets, and per-replica saturation." },
      { id: "cache", title: "Remove repeated work", narration: "Replicas share a cache for hot reads while treating a miss as normal.", activeNodeIds: ["replicas", "cache"], activeEdgeIds: ["replicas-cache"], payload: { label: "Keyed derived result with TTL" }, failure: "A stampede can move all cache-miss traffic to the database at once.", observation: "Hit ratio, evictions, miss latency, and fallback load." },
      { id: "data", title: "Scale reads carefully", narration: "Writes go to the primary; consistency-tolerant reads may use a lagging replica.", activeNodeIds: ["replicas", "primary", "reader"], activeEdgeIds: ["replicas-primary", "primary-reader", "replicas-reader"], payload: { label: "Committed change → asynchronous replica" }, failure: "Reading a replica immediately after a write can return old state.", observation: "Write latency, connection pressure, and replication lag." },
      { id: "async", title: "Buffer slow work", narration: "The request path publishes slow or bursty work to a queue and responds without waiting for completion.", activeNodeIds: ["replicas", "queue"], activeEdgeIds: ["replicas-queue"], payload: { label: "Idempotent job + correlation ID" }, failure: "Unbounded queues can hide overload until work is already severely delayed.", observation: "Oldest-message age, depth, retry rate, and completion latency." },
      { id: "measure", title: "Scale the bottleneck", narration: "Combined signals show whether to add service capacity, database capacity, workers, or no capacity at all.", activeNodeIds: ["replicas", "queue", "observe"], activeEdgeIds: ["replicas-observe", "queue-observe"], payload: { label: "Demand + latency + errors + saturation" }, failure: "Scaling the wrong layer raises cost without improving user outcomes.", observation: "Service objectives, limiting resource, and cost per successful request." },
    ],
    glossaryRefs: ["load-balancer", "replica", "cache", "read-replica", "queue", "observability"],
    checks: [
      { objectiveIndex: 0, question: "What enables a load balancer to use any service replica?", options: ["Shared state is externalized", "Every replica has a different API", "Users choose a server", "DNS stores sessions"], answer: 0, explanation: "Stateless service copies are interchangeable when shared state lives in external systems." },
      { objectiveIndex: 1, question: "Why move slow work to a queue?", options: ["To make it synchronous", "To buffer it outside the user request", "To remove retries", "To store passwords"], answer: 1, explanation: "A queue separates request latency from slower work and absorbs bursts." },
      { objectiveIndex: 2, question: "Which read should usually avoid an asynchronously updated read replica?", options: ["A public catalog page", "A weekly analytics report", "A read immediately after the user's write", "A cached documentation page"], answer: 2, explanation: "Replication lag can hide the user's just-committed change, so consistency-sensitive reads should use the primary or another guarantee." },
    ],
    variants: [
      {
        id: "scaled",
        label: "Scaled architecture",
        description: "Traffic is distributed across replicas with cache, read capacity, and queued work.",
        nodeIds: ["client", "lb", "replicas", "cache", "primary", "reader", "queue", "observe"],
        edgeIds: ["client-lb", "lb-replicas", "replicas-cache", "replicas-primary", "primary-reader", "replicas-reader", "replicas-queue", "replicas-observe", "queue-observe"],
      },
      {
        id: "simple",
        label: "Start-simple monolith",
        description: "One service handles requests and writes to one primary database, with observability but no scaling layers.",
        nodeIds: ["client", "replicas", "primary", "observe"],
        edgeIds: ["client-replicas", "replicas-primary", "replicas-observe"],
        steps: [
          { id: "direct", title: "Serve the request directly", narration: "A client sends the request straight to one application service, keeping the first deployment easy to understand and operate.", activeNodeIds: ["client", "replicas"], activeEdgeIds: ["client-replicas"], payload: { label: "Request + caller context" }, failure: "One service instance creates a single availability and capacity boundary.", observation: "Request rate, latency, errors, and service saturation." },
          { id: "persist", title: "Keep one source of truth", narration: "The application service reads and writes one primary database without cache or replica consistency trade-offs.", activeNodeIds: ["replicas", "primary"], activeEdgeIds: ["replicas-primary"], payload: { label: "Validated command or query" }, failure: "Database pressure can limit the whole system as traffic grows.", observation: "Query latency, connections, locks, storage, and transaction errors." },
          { id: "observe-simple", title: "Measure before adding layers", narration: "Service signals reveal the first real bottleneck so the team adds scaling machinery only when evidence justifies it.", activeNodeIds: ["replicas", "observe"], activeEdgeIds: ["replicas-observe"], payload: { label: "Demand + latency + errors + saturation" }, failure: "Adding distributed components too early raises complexity without improving outcomes.", observation: "Service objectives, limiting resource, growth trend, and cost per request." },
        ],
      },
    ],
    simplification: "Autoscaling delays, distributed transactions, multi-region consistency, sharding, admission control, and cost modeling are omitted.",
    owner: "StackScope editorial",
    sources: [
      { label: "Kubernetes: Horizontal Pod Autoscaling", url: "https://kubernetes.io/docs/concepts/workloads/autoscaling/horizontal-pod-autoscale/" },
      { label: "PostgreSQL: Warm standby", url: "https://www.postgresql.org/docs/current/warm-standby.html" },
    ],
    reviewedAt: "2026-07-10",
  },
];

export const lessonSummaries: LessonSummary[] = lessons.map((lesson) => ({
  slug: lesson.slug,
  title: lesson.title,
  eyebrow: lesson.eyebrow,
  summary: lesson.summary,
  duration: lesson.duration,
  difficulty: lesson.difficulty,
  topics: lesson.topics,
  previewKinds: lesson.nodes.slice(0, 5).map((item) => item.kind),
  layers: Array.from(new Set(lesson.nodes.map((item) => item.kind))),
  searchText: [
    lesson.title,
    lesson.summary,
    lesson.eyebrow,
    ...lesson.topics,
    ...lesson.nodes.map((item) => item.label),
    ...lesson.glossaryRefs,
  ].join(" ").toLowerCase(),
}));
